[files]
extend-exclude = ["resources", "snapshots", ".github/actions/spelling/*"]

[default.extend-words]
hel = "hel"
whos = "whos"
spawnve = "spawnve"
ned = "ned"
poit = "poit"
BA = "BA" # acronym for "Bad Allowed", used in testing.
